/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package kalam-bridge */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "kalam_bridge.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 3 "kalam_bridge_transfer.go"

#include <stdlib.h>
#include <stdint.h>

typedef void (*KalamTransferProgressCallback)(uint64_t, uintptr_t);

static inline void KalamInvokeTransferProgress(
	uintptr_t callback,
	uintptr_t context,
	uint64_t bytes
) {
	if (callback != 0) {
		((KalamTransferProgressCallback)callback)(bytes, context);
	}
}

#line 1 "cgo-generated-wrapper"

#line 3 "kalam_transfer_legacy_download.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 3 "kalam_transfer_legacy_upload.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void Kalam_Init(void);
extern char* Kalam_Scan(void);
extern char* Kalam_ScanResult(void);
extern char* Kalam_OpenSession(char* deviceID);
extern char* Kalam_CloseSession(char* token);
extern char* Kalam_ListFilesSession(char* token, GoUint32 storageID, GoUint32 parentID);
extern char* Kalam_CreateFolderSession(char* token, GoUint32 storageID, GoUint32 parentID, char* folderName);
extern char* Kalam_DeleteObjectSession(char* token, GoUint32 objectID);
extern char* Kalam_RefreshStorageSession(char* token, GoUint32 storageID);
extern char* Kalam_ListFiles(GoUint32 storageID, GoUint32 parentID);
extern void Kalam_FreeString(char* str);
extern GoUint32 Kalam_CreateFolder(GoUint32 storageID, GoUint32 parentID, char* folderName);
extern GoInt32 Kalam_DeleteObject(GoUint32 objectID);
extern GoInt32 Kalam_RefreshStorage(GoUint32 storageID);
extern GoInt32 Kalam_ResetDeviceCache(void);
extern void Kalam_CleanupLeakedStrings(void);
extern void Kalam_CleanupDevicePool(void);
extern void Kalam_SetProgressCallback(uintptr_t cb);
extern GoInt32 Kalam_PrepareTransferTask(char* taskID);
extern GoInt32 Kalam_AbortTransferTask(char* taskID);
extern char* Kalam_DownloadFileSession(char* token, GoUint32 objectID, char* destinationPath, char* taskID, uintptr_t progressCallback, uintptr_t progressContext);
extern void Kalam_CancelTask(char* taskID);
extern char* Kalam_UploadFileSession(char* token, GoUint32 storageID, GoUint32 parentID, char* sourcePath, char* name, GoUint64 size, char* taskID, uintptr_t progressCallback, uintptr_t progressContext);
extern GoInt32 Kalam_DownloadFile(GoUint32 objectID, char* destinationPath, char* taskID);
extern GoInt32 Kalam_UploadFile(GoUint32 storageID, GoUint32 parentID, char* sourcePath, char* taskID);

#ifdef __cplusplus
}
#endif
